version: "3"

services:
    db:
        container_name: cvt-oss-db-reports
        image: postgres
        ports:
            - "5432:5432"
        volumes:
          - "psql-data-reports:/var/lib/postgresql/data"
        environment:
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
    web:
        build: .
        command: ./setup.sh
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db

volumes:
    psql-data-reports:
